### ISSUE TITLE
Portability to OpenFOAM-v9

### ISSUE THREAD

**Issue by rclUPC** [shor-ty/humidityRhoThermo#4]
I am trying to port this library to version 9 of OF. It is not straightforward, since a lot of things have changed. In particular, fvOptions have changed to fvModels and fvConstraints, and thermoPhysical models are including "implementation" and "composite" methods. Anyway, I think that I got it, but the problem is that when I test the new solver with the tutorial "tutorials/RAS/fixedHumidityBC" I get less humidity than when I test it with version 8. About half the quantity to be more precise. I have no idea what can be wrong. 
You can check my version for OF9 in the branch OpenFOAM-v9 of my fork of your project:
https://github.com/rclUPC/humidityRhoThermo/tree/OpenFOAM-v9
Greetings from Spain, and congratulations for your great work with OpenFOAM.

**Comment by rclUPC** [comment]
This problem has been solved with the last commit. The mistake was in `calculate()` of `heRhoHumidityThermo.C`. I didn't realize that the density had to be removed.

**Comment by shor-ty** [comment]
Thanks for your update.
