### ISSUE TITLE
thermo: filename reading issues in windows

### ISSUE THREAD

**Issue by sawjam** [shor-ty/humidityRhoThermo#5]
Working on Windows 10 with WSL(ubuntu) openfaom v9 could only get [rclUPC](https://github.com/rclUPC/humidityRhoThermo)] fork to run solver without error. Note I am a beginer with OpenFoam!
BUT
issue is with : in file name therm:relHum etc as windows 10 in ParaView will not recognise the data, need to rename all files in time folders in order for data to be read i.e. therm-relHum 
used < find . -name "*[:]*" -exec rename 's/\:/-/g' {} + >  in root of case in ubuntu terminal, then could see therm time data in ParaView

Really appreciate the work on the humidity app - thank you

**Comment by shor-ty** [comment]
Known issue which is related to windows. I was following the syntax provided by OpenFOAM. As OpenFOAM is not distributed for windows officially, I will not provide a patch. Hence, you need to rename everything (use a script) or create a wrapper, or change the code accordingly. 

Hence, the issue will be closed.
